[tool.poetry]
name = "python-stack"
version = "0.0.0"
description = "python-stack"
authors = ["stoiet"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
