name: Save image
description: Save docker image as an artifact

inputs:
  IMAGE_NAME:
    description: IMAGE_NAME
    required: true
  IMAGE_VERSION:
    description: IMAGE_VERSION
    required: true
    default: latest

runs:
  using: composite
  steps:
    - run: IMAGE_NAME=${{ inputs.IMAGE_NAME }} IMAGE_VERSION=${{ inputs.IMAGE_VERSION }} make save-image
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.IMAGE_NAME }}
        path: /tmp/${{ inputs.IMAGE_NAME }}.tar.gz
        if-no-files-found: error
        retention-days: 1