name: Load image
description: Load docker image as an artifact

inputs:
  IMAGE_NAME:
    description: IMAGE_NAME
    required: true
  IMAGE_VERSION:
    description: IMAGE_VERSION
    required: true
    default: latest

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.IMAGE_NAME }}-${{ inputs.IMAGE_VERSION }}
        path: /tmp

    - run: make load-image
      shell: bash
      env:
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
