name: Load image
description: Load docker image as an artifact

inputs:
  IMAGE_NAME:
    description: IMAGE_NAME
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.IMAGE_NAME }}
        path: /tmp

    - run: IMAGE_NAME=${{ inputs.IMAGE_NAME }} make load-image
      shell: bash
