cache-dir = "~/workdir/.cache/poetry"

[experimental]
system-git-client = false

[installer]
modern-installation = true
parallel = true

[solver]
lazy-wheel = true

[virtualenvs]
create = true
in-project = true
options.always-copy = true
options.no-pip = true
options.no-setuptools = true
options.system-site-packages = false
path = "~/workdir/.venv"
prefer-active-python = false
prompt = "{project_name}"

[keyring]
enabled = false
