name: Clean artifacts
description: Clean artifacts

inputs:
  ARTIFACT_NAME:
    description: ARTIFACT_NAME
    required: true

runs:
  using: composite
  steps:
    - name: remove workflow artifact
      run: |
        for id in $(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts?per_page=1000 --jq '.artifacts[] | select(.name=="${{ inputs.ARTIFACT_NAME }}") | .id'); do
          gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts/$id;
          echo $id;
        done
      shell: bash

    - name: remove expired artifacts
      run: |
        for id in $(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts?per_page=1000 --jq ".artifacts[] | select(.expired) | .id"); do
          gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts/$id;
          echo $id;
        done
      shell: bash
