name: Pipeline

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build
      - uses: ./.github/actions/image-save
        with:
          IMAGE_NAME: python-stack-image

  check:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: python-stack-image
      - run: make images
