name: Pipeline

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

env:
  IMAGE_NAME: python-stack-image
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - run: make build

      - uses: ./.github/actions/image-save
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

  check:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/docker-scout
      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make images
      - run: echo ${{ secrets.DOCKER_SCOUT_REGISTRY_TOKEN }} | docker login --username ${{ secrets.DOCKER_SCOUT_REGISTRY_USER }} --password-stdin
      - run: make scout
      - run: make dive
      - run: make grype
      - run: make trivy

  clear:
    runs-on: ubuntu-24.04
    needs: [check]
    if: ${{ always() }}
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/clear-artifacts
        with:
          ARTIFACT_NAME: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_VERSION }}
