name: Pipeline

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

env:
  IMAGE_NAME: python-stack-image
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - run: make build
      - run: make images

      - uses: ./.github/actions/image-save
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

  check-scout:
    runs-on: ubuntu-24.04
    needs: [build-image]
    permissions: {}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/docker-scout
        with:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make scout

  check-dive:
    runs-on: ubuntu-24.04
    needs: [build-image]
    permissions: {}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make dive

  check-grype:
    runs-on: ubuntu-24.04
    needs: [build-image]
    permissions: {}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make grype

  check-trivy:
    runs-on: ubuntu-24.04
    needs: [build-image]
    permissions: {}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make trivy

  cleanup:
    runs-on: ubuntu-24.04
    needs: [check-scout, check-dive, check-grype, check-trivy]
    if: ${{ always() }}
    permissions:
      actions: write
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - uses: ./.github/actions/clear-artifacts
        with:
          ARTIFACT_NAME: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_VERSION }}
