name: Pipeline

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

env:
  IMAGE_NAME: python-stack-image
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: make build
      
      - uses: ./.github/actions/image-save
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

  check:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/image-load
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - run: make images
